# WARNING!
# This file is NOT ignored by source control! Do NOT put sensitive data here!
#
# Use ENV for all non-dev configuration, e.g. API keys.
#
# Specifically, using the `dotenv` gem, we can just define ENV variables in the `.env` file.
# Also note that you can create .env.{{ Rails.env }} files, e.g. .env.development and .env.staging

#
# Editorial note - jbinto 2014-04-15:
#
#   It's a bit of a mess, between the new Rails 4.1 convention (put secrets here), the 12-factor convention
#   (put them in ENV), and gems like Figaro and Dotenv that let you put them in a file that acts like a psuedo ENV.
#
#   This seems to give me the best of all worlds. Some of the boilerplate code accesses `Rails.application.secrets`,
#   so I need this file. Specifically, asset precompilation needs to load the entire environment, and Devise complains
#   if a `secret_key_base` isn't set.
#
#   If I need to hot-change anything, I can always use the real ENV.
#
#   It should work on a 12-factor provider like Heroku or dokku, but isn't tested.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  gmail_username: Your_Username
  gmail_password: Your_Password
  secret_key_base: ef2955318d4eb80b149043cd19b1da21743f4a9b60f75ac317f8164105ed4d44cac7671dc901b694b50818bf1707bdf42073e82304a3e0399d0e8af4727113e4

test:
  secret_key_base: 31c961df4ba093cfc6f118054c8e27f20d293e332dfe8edc633ca43f5f364d907591adf6fe5db2c470ba2ca7fb6df6f084b02696cfec10eeb152a89cd6085687


staging:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
